name: Compilar Choque no Sistema APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5 \
            libncurses5-dev \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Instalar Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Compilar APK
        run: |
          buildozer -v android debug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: choque-no-sistema-apk
          path: bin/*.apk
